// <auto-generated />
using System;
using LeagueLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueLibrary.Migrations
{
    [DbContext(typeof(LeagueContext))]
    [Migration("20200517223242_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueLibrary.Models.Speler", b =>
                {
                    b.Property<int>("SpelerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RugNummer")
                        .HasColumnType("int");

                    b.Property<int?>("TeamStamNummer")
                        .HasColumnType("int");

                    b.Property<int>("Waarde")
                        .HasColumnType("int");

                    b.HasKey("SpelerID");

                    b.HasIndex("TeamStamNummer");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("LeagueLibrary.Models.Team", b =>
                {
                    b.Property<int>("StamNummer")
                        .HasColumnType("int");

                    b.Property<string>("Bijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StamNummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LeagueLibrary.Models.Transfer", b =>
                {
                    b.Property<int>("TransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NieuweClubStamNummer")
                        .HasColumnType("int");

                    b.Property<int?>("OudeClubStamNummer")
                        .HasColumnType("int");

                    b.Property<int?>("SpelerID")
                        .HasColumnType("int");

                    b.Property<int>("TransferPrijs")
                        .HasColumnType("int");

                    b.HasKey("TransferID");

                    b.HasIndex("NieuweClubStamNummer");

                    b.HasIndex("OudeClubStamNummer");

                    b.HasIndex("SpelerID");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("LeagueLibrary.Models.Speler", b =>
                {
                    b.HasOne("LeagueLibrary.Models.Team", "Team")
                        .WithMany("Spelers")
                        .HasForeignKey("TeamStamNummer");
                });

            modelBuilder.Entity("LeagueLibrary.Models.Transfer", b =>
                {
                    b.HasOne("LeagueLibrary.Models.Team", "NieuweClub")
                        .WithMany()
                        .HasForeignKey("NieuweClubStamNummer");

                    b.HasOne("LeagueLibrary.Models.Team", "OudeClub")
                        .WithMany()
                        .HasForeignKey("OudeClubStamNummer");

                    b.HasOne("LeagueLibrary.Models.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerID");
                });
#pragma warning restore 612, 618
        }
    }
}
